services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: ${DB_HOST}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - mongo_spaghe:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}  
    networks:
      - spaghettinetwork
  backend:
    build: .
    container_name: ${APP_HOST}
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    networks:
      - spaghettinetwork
      - nginx-proxy
    environment:
      VIRTUAL_HOST: spaghettiapi.luispadua.com
      LETSENCRYPT_HOST: spaghettiapi.luispadua.com
      LETSENCRYPT_EMAIL: admin@spaghettiapi.luispadua.com
volumes:
  node_modules:
  mongo_spaghe:
networks:
  spaghettinetwork:
  nginx-proxy:
    external: true